name: app
description: "Notas culinárias"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.10+1
  camera: ^0.11.0+2 
  qr_code_scanner: ^1.0.0
  mobx: ^2.2.0
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  firebase_database: ^11.1.3
  provider: ^6.1.2
  flutter_mobx: ^2.2.1+1
  http: ^1.2.2
  url_launcher: ^6.1.7
  android_intent_plus: ^3.0.0

dependency_overrides:
  camera_android_camerax: 0.6.7 
  video_player_android: 2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.0.0
  mobx_codegen: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/back01.png
    - assets/images/back02.png
    - assets/images/back03.png
    - assets/images/back04.png
    - assets/images/home.svg
    - assets/images/camera.svg
    - assets/images/receipt.svg
    - assets/fonts/
  fonts:
    - family: PP Neue Montreal
      fonts:
        - asset: assets/fonts/PPNeueMontreal-Book.otf
          weight: 400
        - asset: assets/fonts/PPNeueMontreal-Bold.otf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.otf
          weight: 400
        - asset: assets/fonts/Inter-Italic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/Inter-Light.otf
          weight: 300
        - asset: assets/fonts/Inter-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/Inter-Bold.otf
          weight: 700
