name: app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/back01.png
    - assets/images/back02.png
    - assets/images/back03.png
    - assets/images/back04.png
    - assets/fonts/
  fonts:
    - family: PP Neue Montreal
      fonts:
        - asset: assets/fonts/PPNeueMontreal-Book.otf
          weight: 400
        - asset: assets/fonts/PPNeueMontreal-Bold.otf
          weight: 700
