// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6T8gU0hDE1tMqB-3sf4LVIDlFqsl759A',
    appId: '1:305798928293:web:d2e5aea397135c1e183a4c',
    messagingSenderId: '305798928293',
    projectId: 'tcc2-notasculinarias',
    databaseURL: "https://tcc2-notasculinarias-default-rtdb.firebaseio.com",
    authDomain: 'tcc2-notasculinarias.firebaseapp.com',
    storageBucket: 'tcc2-notasculinarias.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6T8gU0hDE1tMqB-3sf4LVIDlFqsl759A',
    appId: '1:305798928293:android:ec187ee8c795b30d183a4c',
    messagingSenderId: '305798928293',
    projectId: 'tcc2-notasculinarias',
    databaseURL: "https://tcc2-notasculinarias-default-rtdb.firebaseio.com",
    authDomain: 'tcc2-notasculinarias.firebaseapp.com',
    storageBucket: 'tcc2-notasculinarias.appspot.com',
  );
}
